# See https://upptime.js.org/docs/configuration for more options
owner: SRESchool
repo: AllProfessnow-monitor-upptime
user-agent: SRESchool
skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false

assignees:
  - SRESchool # GitHub username to assign issues

status-website:
  cname: # Add custom domain here if you have one (e.g., status.professnow.com)
  baseUrl: /AllProfessnow-monitor-upptime
  logoUrl: https://upptime.js.org/img/icon.svg
  name: AllProfessnow Uptime Monitor
  introTitle: "Uptime and SSL Status for Multiple Websites"
  introMessage: "Monitoring uptime and SSL certificates for professnow.com, ireviewed.in, wakilsahab.in, astropilot.co, dronesnow.in, and desinri.com using Upptime."
  
navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
sites:
  - name: Professnow
    url: https://professnow.com
    slug: professnow
    checkSSL: true
  - name: IReviewed
    url: https://ireviewed.in
    slug: ireviewed
    checkSSL: true
  - name: WakilSahab
    url: https://wakilsahab.in
    slug: wakilsahab
    checkSSL: true
  - name: AstroPilot
    url: https://astropilot.co
    slug: astropilot
    checkSSL: true
  - name: DronesNow
    url: https://dronesnow.in
    slug: dronesnow
    checkSSL: true
  - name: Desinri
    url: https://desinri.com
    slug: desinri
    checkSSL: true

workflowSchedule:
  graphs: "*/5 * * * *" # Every day at midnight
  responseTime: "*/5 * * * *" # Every day at midnight
  staticSite: "*/5 * * * *" # Every day at midnight
  summary: "*/5 * * * *" # Every day at midnight
  updateTemplate: "*/5 * * * *" # Every day at midnight
  updates: "*/5 * * * *" # Every day at midnight
  uptime: "*/5 * * * *" # Every 5 minutes
